In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [22]:
# Preparing paths
data_path = "C:\dev\DATA\MRH"

heart_rate_path = os.path.join(data_path, "heart_rate")

motion_path = os.path.join(data_path, "motion")

labels_path = os.path.join(data_path, "labels")

# Obtaining a list with all users
heart_rate_list = os.listdir(heart_rate_path)
motion_list = os.listdir(motion_path)
labels_list = os.listdir(labels_path)

# Checking that we have data of the 31 users in all the lists created
assert len(heart_rate_list) == 31, "Error, missing users in heart rate list"
assert len(motion_list) == 31, "Error, missing users in motion list"
assert len(labels_list) == 31, "Error, missing users in labels list"

In [40]:
labels_list[0], motion_list[0], heart_rate_list[0]

('1066528_labeled_sleep.txt',
 '1066528_acceleration.txt',
 '1066528_heartrate.txt')

In [29]:
user_1_labels = np.loadtxt(os.path.join(labels_path, labels_list[0]))

user_1_labels

array([[    0.,     0.],
       [   30.,     0.],
       [   60.,     0.],
       ...,
       [28470.,     0.],
       [28500.,     0.],
       [28530.,     0.]])

In [39]:
user_1_motion = np.loadtxt(os.path.join(motion_path, motion_list[0]))

user_1_motion

array([[-2.16848465e+04,  7.08010000e-03,  6.40900000e-04,
        -9.87594600e-01],
       [-2.16848171e+04,  4.15040000e-03,  6.25600000e-04,
        -9.90554800e-01],
       [-2.16848079e+04,  4.15040000e-03,  1.11390000e-03,
        -9.90081800e-01],
       ...,
       [ 2.86265419e+04, -5.52734400e-01, -2.99988000e-02,
        -8.10440100e-01],
       [ 2.86265428e+04, -5.53710900e-01, -3.05023000e-02,
        -8.11431900e-01],
       [ 2.86265436e+04, -5.54718000e-01, -2.99988000e-02,
        -8.09021000e-01]])

In [38]:
user_1_heart_rate = np.loadtxt(os.path.join(heart_rate_path, heart_rate_list[0]), delimiter=',')

user_1_heart_rate

array([[-3.55241740e+05,  8.60000000e+01],
       [-3.51407999e+05,  6.70000000e+01],
       [-3.51277368e+05,  1.41000000e+02],
       ...,
       [ 2.91101643e+04,  7.50000000e+01],
       [ 3.43346538e+04,  8.10000000e+01],
       [ 3.44911535e+04,  6.50000000e+01]])